#!/bin/bash
set -e

REPO="${AIDE_REPO:-$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)}"
NOTES_DIR="${NOTES_DIR:-$HOME/notes}"
CONTEXT_DIR="${CONTEXT_DIR:-$HOME/.notes-context}"
FISH_CONF_DIR="${FISH_CONF_DIR:-$HOME/.config/fish/conf.d}"

mkdir -p "$NOTES_DIR"
mkdir -p "$CONTEXT_DIR"
mkdir -p "$CONTEXT_DIR/projects"
mkdir -p "$FISH_CONF_DIR"

# Always regenerate manifest so script paths stay current after a repo move
manifest="$CONTEXT_DIR/manifest.md"
{
  printf "# aide manifest (auto-generated by install.sh)\n"
  printf "cleanup_planner: %s/scripts/cleanup_planner.py\n" "$REPO"
  printf "filter_emails: %s/scripts/filter_emails.py\n" "$REPO"
} > "$manifest"

for f in history_index.md user-planner.md daily-goals.md; do
  target="$CONTEXT_DIR/$f"
  if [ ! -f "$target" ]; then
    case "$f" in
      history_index.md) printf "## Recent Files\n" > "$target" ;;
      *)                touch "$target" ;;
    esac
  fi
done

# Fish
fish_file="$FISH_CONF_DIR/aide.fish"
path_line="fish_add_path $REPO/scripts"
if [ ! -f "$fish_file" ] || ! grep -qF "$path_line" "$fish_file"; then
  printf "%s\n" "$path_line" >> "$fish_file"
fi

# Zsh (macOS default) and bash
add_to_shell() {
  local rc_file="$1"
  if grep -qF "# added by aide" "$rc_file" 2>/dev/null; then
    return
  fi
  printf "\nexport PATH=\"%s/scripts:\$PATH\" # added by aide\n" "$REPO" >> "$rc_file"
}

add_to_shell "$HOME/.zshrc"
[ -f "$HOME/.bashrc" ] && add_to_shell "$HOME/.bashrc"

filter_file="$CONTEXT_DIR/email-filter.md"
if [ ! -f "$filter_file" ]; then
  cat > "$filter_file" <<'EOF'
# Email noise blocklist

Senders matching any pattern below are excluded before the LLM sees your emails.
Add one pattern per line — plain text substring match against the sender address.

- noreply@
- no-reply@
- notifications@
- discord.com
- github.com
- linkedin.com
- marketing@
- newsletter@
EOF
fi

printf "aide installed.\n"
printf "  notes dir:    %s\n" "$NOTES_DIR"
printf "  context dir:  %s\n" "$CONTEXT_DIR"
printf "  fish config:  %s\n" "$fish_file"
